#!/usr/bin/env node
'use strict';
/**
 * 천운 v7.73 — 클라이언트 천문/역법 엔진 **기계 생성기** (관통 #7 · 안 (가))
 * ============================================================================
 * 무엇을 하는가
 *   `api/_engine/{astro,lunar,recompute}.js` 세 파일을 읽어, 브라우저에서
 *   그대로 도는 **단일 IIFE 블록**(`const CW_ENGINE = (function(){...})()`)으로
 *   기계 변환하고 `index.html` 의 마커 구간에 반입한다.
 *
 * 왜 필요한가 (에이전트 C 진단 §5-4)
 *   안 (가)(클라 알고리즘을 서버와 동일하게 교체)의 유일한 구조적 약점은
 *   **코드 2벌 드리프트**다. 손으로 베끼면 다음 세션에 반드시 갈린다.
 *   ⟹ 반입 블록을 손으로 쓰지 않고 **엔진에서 생성**하고, 산출물과 원본의
 *      sha256 을 짝으로 못박아 어긋나면 즉시 FAIL 하게 만든다.
 *
 * ★2026-08-06 v7.73-c (에이전트 D2 · 관통 E-4) — **커밋되는 경로로 이동**
 *   종전 위치 `_v773_work/` 는 `.gitignore:50` 의 언더바-v-별표 규칙에 걸려
 *   **커밋되지 않았다**(실측: git check-ignore -v _v773_work/gen_client_astro.js
 *   → .gitignore:50 이 그 경로를 무시한다고 보고).
 *   ⟹ 커밋 직후 「코드 2벌 드리프트를 막는 유일한 도구」가 리포에 없어지는 상태였다.
 *      v7.72 I-42 의 정확한 재발이므로 `tools/` 로 옮긴다(게이트 P-1 의 1순위 후보).
 *   ★`BEGIN` 마커 문자열은 **바꾸지 않는다** — index.html 안에 이미 그 문자열이
 *     박혀 있고 이 세션에서 index.html 은 확정 수리본(수정 금지)이다. 마커 안의
 *     경로 표기는 이 주석이 정정한다.
 *
 * 사용법
 *   node tools/gen_client_astro.js            # 생성 → 산출물 + 핀 파일만 씀
 *   node tools/gen_client_astro.js --apply    # index.html 의 마커 구간까지 교체
 *   node tools/gen_client_astro.js --check    # index.html 이 최신 엔진과 일치하는지 검사
 *                                            #   (게이트용. 불일치면 exit 1)
 *
 * 산출물
 *   tools/cw_engine_port.pins.json              원본 3파일 + 블록의 sha256 (★커밋 대상)
 *   <tmp>/cw_client_port_gen/cw_engine_port.gen.js  생성된 블록 본문(마커 제외 · 작업 산출물)
 *
 * 변환 규칙 (전부 기계적 · 사람 판단 0)
 *   R1. 주석 전면 제거 (문자열·정규식 리터럴을 보존하는 렉서로)
 *   R2. `'use strict';` 제거 — IIFE 머리에서 한 번만 선언한다
 *   R3. `require('./astro.js')` · `require('./lunar.js')` 줄 제거
 *   R4. `module.exports = {...};` 제거
 *   R5. 모듈 접두사 `A.` · `LU.` 제거 (같은 스코프로 합쳐지므로)
 *   R6. 세 파일을 astro → lunar → recompute 순으로 이어 붙임
 *   R7. ADAPTER(아래 상수) 를 뒤에 붙이고 return 문으로 노출
 *
 * ★ADAPTER 만이 이 파일에서 손으로 쓰인 코드다. 엔진 함수만 호출하며
 *   역법·천문 판정을 **한 줄도 다시 구현하지 않는다**(드리프트 표면 0).
 * ============================================================================
 */

const fs = require('fs');
const os = require('os');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.resolve(__dirname, '..');
const ENGINE_DIR = path.join(ROOT, 'api', '_engine');
const SRC_FILES = ['astro.js', 'lunar.js', 'recompute.js'];
const INDEX = path.join(ROOT, 'index.html');
// ★핀은 이 도구와 **같은 커밋 단위**(tools/)에 둔다. 도구만 커밋되고 핀이 ignore 되면
//   P-4·P-5 가 「핀 부재」로 무력해진다(관통 E-4 의 절반).
const PINS = path.join(__dirname, 'cw_engine_port.pins.json');
// 생성 본문은 **작업 산출물**이다. 리포에 두면 반입 블록의 2벌째 사본이 되어
// 드리프트 표면을 스스로 만든다 ⟹ 임시 디렉터리에 쓴다(--check 는 쓰지 않는다).
const OUT_DIR = process.env.CW_GEN_OUT || path.join(os.tmpdir(), 'cw_client_port_gen');
const OUT_JS = path.join(OUT_DIR, 'cw_engine_port.gen.js');

const BEGIN = '// ==== CW_ENGINE_PORT BEGIN (generated by _v773_work/gen_client_astro.js - DO NOT EDIT BY HAND) ====';
const END = '// ==== CW_ENGINE_PORT END ====';

const sha256 = (s) => crypto.createHash('sha256').update(s, 'utf8').digest('hex');

// ────────────────────────────────────────────────────────────────────────────
// R1. 주석 제거 렉서 — 문자열('/"/`)과 정규식 리터럴 안의 `//` 를 건드리지 않는다
// ────────────────────────────────────────────────────────────────────────────
function stripComments(src) {
  let out = '';
  let prev = '';                 // 직전 유의미 문자 (정규식 리터럴 판별용)
  for (let i = 0; i < src.length;) {
    const c = src[i], c2 = src[i + 1];
    if (c === '/' && c2 === '/') { while (i < src.length && src[i] !== '\n') i++; continue; }
    if (c === '/' && c2 === '*') {
      i += 2;
      while (i < src.length && !(src[i] === '*' && src[i + 1] === '/')) i++;
      i += 2; out += ' '; continue;
    }
    if (c === '"' || c === "'" || c === '`') {
      out += c; i++;
      while (i < src.length) {
        if (src[i] === '\\') { out += src[i] + (src[i + 1] || ''); i += 2; continue; }
        out += src[i];
        if (src[i] === c) { i++; break; }
        i++;
      }
      prev = c; continue;
    }
    if (c === '/' && !/[)\]}\w$]/.test(prev)) {   // 나눗셈이 아니라 정규식 리터럴
      out += c; i++;
      let inClass = false;
      while (i < src.length) {
        if (src[i] === '\\') { out += src[i] + (src[i + 1] || ''); i += 2; continue; }
        if (src[i] === '[') inClass = true;
        else if (src[i] === ']') inClass = false;
        else if (src[i] === '/' && !inClass) { out += src[i]; i++; break; }
        out += src[i]; i++;
      }
      while (i < src.length && /[a-z]/.test(src[i])) { out += src[i]; i++; }
      prev = '/'; continue;
    }
    out += c;
    if (!/\s/.test(c)) prev = c;
    i++;
  }
  return out;
}

/** 공백만 남은 줄 정리 + 연속 빈 줄 1줄로 */
function tidy(src) {
  return src.split('\n').map((l) => l.replace(/[ \t]+$/, ''))
    .join('\n').replace(/\n{3,}/g, '\n\n').replace(/^\n+/, '').replace(/\n+$/, '') + '\n';
}

// ────────────────────────────────────────────────────────────────────────────
// ★ADAPTER — 이 파일에서 유일하게 손으로 쓰인 코드.
//   index.html 이 쓰던 함수 시그니처를 엔진 위에 그대로 얹는 얇은 층이며,
//   역법·천문 계산을 재구현하지 않는다.
// ────────────────────────────────────────────────────────────────────────────
const ADAPTER = `
/** 음력 (ly,lm,윤달여부) 달의 일수(29 또는 30). 없는 달이면 0. */
function lunarMonthLen(ly, lm, isLeap) {
  const s = lunarToSolar(ly, lm, 1, !!isLeap);
  if (!s) return 0;
  const j = gregorianToJDN(s.y, s.m, s.d);
  const months = _monthsCovering(j);
  for (let i = 0; i < months.length; i++) {
    const mo = months[i];
    if (j >= mo.startJdn && j <= mo.endJdn) return mo.endJdn - mo.startJdn + 1;
  }
  return 0;
}

/** 그 해 윤달의 일수(윤달 없으면 0) */
function lunarLeapLen(ly) {
  const m = leapMonthOf(ly);
  return m ? lunarMonthLen(ly, m, true) : 0;
}

/** 엔진이 보증하는 입력 구간 (recompute.parseBirthDate 와 동일 정의) */
const RANGE = { minY: 1900, maxY: 2050 };
`;

const EXPORTS = `
return {
  recompute: recompute,
  solarToLunar: solarToLunar,
  lunarToSolar: lunarToSolar,
  leapMonthOf: leapMonthOf,
  lunarMonthLen: lunarMonthLen,
  lunarLeapLen: lunarLeapLen,
  gregorianToJDN: gregorianToJDN,
  jdnToGregorian: jdnToGregorian,
  majorTermsOfYear: majorTermsOfYear,
  parseBirthDate: parseBirthDate,
  normHourIdx: normHourIdx,
  compatPillarLine: compatPillarLine,
  compatIlganLabel: compatIlganLabel,
  RANGE: RANGE
};
`;

// ────────────────────────────────────────────────────────────────────────────
// 생성
// ────────────────────────────────────────────────────────────────────────────
function build() {
  const srcHashes = {};
  const parts = [];

  for (const f of SRC_FILES) {
    const raw = fs.readFileSync(path.join(ENGINE_DIR, f), 'utf8');
    srcHashes[f] = sha256(raw);

    let s = stripComments(raw);
    s = s.replace(/^\s*'use strict';\s*$/m, '');                       // R2
    s = s.replace(/^\s*const\s+(A|LU)\s*=\s*require\([^)]*\);\s*$/gm, ''); // R3
    s = s.replace(/module\.exports\s*=\s*\{[^}]*\};?/g, '');           // R4

    // R5 — 모듈 접두사 제거. 단, astro.js 안의 지역변수 A(Meeus 보정항 배열)와
    //      충돌하지 않는지 기계로 확인한 뒤에만 지운다.
    if (f === 'astro.js') {
      const hits = (s.match(/(^|[^\w$.])A\./g) || []).length;
      if (hits !== 0) throw new Error('astro.js 안에 A. 참조가 있다 — R5 가 안전하지 않다: ' + hits);
    }
    s = s.replace(/(^|[^\w$.])A\.(?=[A-Za-z_$])/g, '$1');
    s = s.replace(/(^|[^\w$.])LU\.(?=[A-Za-z_$])/g, '$1');

    parts.push('// ---- ' + f + ' ----\n' + tidy(s));
  }

  const core = parts.join('\n');
  const body = tidy(core + '\n' + stripComments(ADAPTER) + '\n' + EXPORTS);

  // 중복 최상위 선언 검사 (IIFE 안에서 SyntaxError 가 되는 유일한 실패 모드)
  const decl = {};
  for (const m of body.matchAll(/^(?:function|const|let|var)\s+([A-Za-z_$][\w$]*)/gm)) {
    if (decl[m[1]]) throw new Error('최상위 중복 선언: ' + m[1]);
    decl[m[1]] = true;
  }

  const wrapped =
    'const CW_ENGINE = (function () {\n' +
    "'use strict';\n" +
    body +
    '})();\n';

  const blockSha = sha256(wrapped);
  const header =
    BEGIN + '\n' +
    '// src: ' + SRC_FILES.map((f) => f + '@' + srcHashes[f].slice(0, 16)).join(' ') + '\n' +
    '// block-sha256: ' + blockSha + '\n';

  return { srcHashes, wrapped, blockSha, text: header + wrapped + END + '\n' };
}

function readIndexBlock(html) {
  const b = html.indexOf(BEGIN);
  const e = html.indexOf(END);
  if (b === -1 || e === -1) return null;
  const seg = html.slice(b, e + END.length + 1);
  // 마커 3줄(BEGIN·src·block-sha256) 뒤부터 END 직전까지가 본문
  const lines = seg.split('\n');
  const body = lines.slice(3, lines.length - 2).join('\n') + '\n';
  return { start: b, end: e + END.length, seg, body };
}

function main() {
  const mode = process.argv[2] || '';
  const built = build();

  if (mode === '--check') {
    const html = fs.readFileSync(INDEX, 'utf8');
    const cur = readIndexBlock(html);
    if (!cur) { console.error('FAIL: index.html 에 CW_ENGINE_PORT 마커가 없다'); process.exit(1); }
    if (cur.body !== built.wrapped) {
      console.error('FAIL: index.html 의 반입 블록이 현재 api/_engine/* 에서 생성한 것과 다르다.');
      console.error('      → node _v773_work/gen_client_astro.js --apply 로 재생성하십시오.');
      process.exit(1);
    }
    if (fs.existsSync(PINS)) {
      const pins = JSON.parse(fs.readFileSync(PINS, 'utf8'));
      for (const f of SRC_FILES) {
        if (pins.sources[f] !== built.srcHashes[f]) {
          console.error('FAIL: ' + f + ' 의 sha256 이 핀과 다르다 (엔진이 바뀌었다)');
          process.exit(1);
        }
      }
      if (pins.block_sha256 !== built.blockSha) { console.error('FAIL: block sha256 불일치'); process.exit(1); }
    }
    console.log('OK: index.html 반입 블록 == api/_engine/* 생성물 (block ' + built.blockSha.slice(0, 16) + ')');
    return;
  }

  fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.writeFileSync(OUT_JS, built.wrapped, 'utf8');
  fs.writeFileSync(PINS, JSON.stringify({
    _schema: 'cw_engine_port/v1',
    _note: '관통 #7 안 (가) — index.html 의 CW_ENGINE_PORT 블록은 api/_engine/* 에서 기계 생성된다. '
      + '엔진을 고치고 index.html 을 재생성하지 않으면 gen_client_astro.js --check 가 FAIL 한다.',
    generator: '_v773_work/gen_client_astro.js',
    target: 'index.html',
    marker_begin: BEGIN,
    marker_end: END,
    sources: built.srcHashes,
    block_sha256: built.blockSha,
    block_bytes: Buffer.byteLength(built.wrapped, 'utf8'),
    generated_at: new Date().toISOString()
  }, null, 2) + '\n', 'utf8');

  if (mode === '--apply') {
    const html = fs.readFileSync(INDEX, 'utf8');
    const cur = readIndexBlock(html);
    if (!cur) { console.error('FAIL: index.html 에 CW_ENGINE_PORT 마커가 없다. 최초 반입은 수동으로 마커를 넣으십시오.'); process.exit(1); }
    const next = html.slice(0, cur.start) + built.text.replace(/\n$/, '') + html.slice(cur.end);
    fs.writeFileSync(INDEX, next, 'utf8');
    console.log('applied → index.html (' + built.wrapped.length + ' chars)');
  }
  console.log('block sha256 = ' + built.blockSha);
  console.log('bytes        = ' + Buffer.byteLength(built.wrapped, 'utf8'));
  for (const f of SRC_FILES) console.log('  ' + f + ' = ' + built.srcHashes[f]);
}

if (require.main === module) main();
module.exports = { build, stripComments, readIndexBlock, BEGIN, END };
